name: CI Pipeline

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip and uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install -r pyproject.toml
      - name: Run linter
        run: uv run make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install pip and uv
        run: |
          python -m pip install --upgrade pip
          pip install uv
      - name: Create virtual environment
        run: uv venv
      - name: Install dependencies
        run: uv pip install -r pyproject.toml
      - name: Run tests
        run: uv run make test
